// src/prompts/promptCatalog.ts
import type { PromptId, PromptSpec } from "../domain/types.js";
/**
 * Prompt catalog keyed by promptId.
 * IMPORTANT: promptId is the canonical identifier you store on each capture.
 */
export const PROMPT_CATALOG: Partial<Record<PromptId, PromptSpec>> = {

  // ======================
  // IE — SocialEnergyAxis (template: 25 prompts, A only)
  // ======================

  // 1) energyDirection (IDs 1–5)
  "VK.IE.1A.v1": {
    id: "VK.IE.1A.v1",
    dimensionId: "IE",
    subAxisId: "energyDirection",
    variant: "A",
    version: "v1",
    phase: 1,
    promptType: "freeRecall",
    intensity: 2,
    instructionText: "What do you remember?",
    modality: "text",
    stimulusRef: {
      kind: "inlineText",
      text: "Noisy conference lunch. Everyone talking. One empty hallway.",
    },
    exposureMs: 8000,
    responseMode: "spoken",
  },
  "VK.IE.2A.v1": {
    id: "VK.IE.2A.v1",
    dimensionId: "IE",
    subAxisId: "energyDirection",
    variant: "A",
    version: "v1",
    phase: 2,
    promptType: "openInterpretation",
    intensity: 3,
    instructionText: "Respond with single-word adjectives or nouns ONLY.",
    modality: "text",
    stimulusRef: {
      kind: "inlineText",
      text: "Weekend alone. No plans.",
    },
    responseMode: "spoken",
  },
  "VK.IE.3A.v1": {
    id: "VK.IE.3A.v1",
    dimensionId: "IE",
    subAxisId: "energyDirection",
    variant: "A",
    version: "v1",
    phase: 3,
    promptType: "microDecision",
    intensity: 3,
    instructionText: "Choose.",
    modality: "text",
    stimulusRef: {
      kind: "inlineText",
      text: "One free hour: people or none?",
    },
    responseMode: "spoken",
  },
  "VK.IE.4A.v1": {
    id: "VK.IE.4A.v1",
    dimensionId: "IE",
    subAxisId: "energyDirection",
    variant: "A",
    version: "v1",
    phase: 4,
    promptType: "errorDetection",
    intensity: 4,
    instructionText: "Anything off?",
    modality: "text",
    stimulusRef: {
      kind: "inlineText",
      text: "Weekend retreat. No private space anywhere.",
    },
    responseMode: "spoken",
  },
  "VK.IE.5A.v1": {
    id: "VK.IE.5A.v1",
    dimensionId: "IE",
    subAxisId: "energyDirection",
    variant: "A",
    version: "v1",
    phase: 5,
    promptType: "projectionContinuation",
    isWildcard: true,
    intensity: 3,
    instructionText: "What do you do next?",
    modality: "text",
    stimulusRef: {
      kind: "inlineText",
      text: "Two days alone. Energy dropping.",
    },
    responseMode: "spoken",
  },

  // 2) processingHabitat (IDs 6–10)
  "VK.IE.6A.v1": {
    id: "VK.IE.6A.v1",
    dimensionId: "IE",
    subAxisId: "processingHabitat",
    variant: "A",
    version: "v1",
    phase: 1,
    promptType: "freeRecall",
    intensity: 2,
    instructionText: "What do you remember?",
    modality: "text",
    stimulusRef: {
      kind: "inlineText",
      text: "Question asked. You had an answer. Someone spoke first.",
    },
    exposureMs: 8000,
    responseMode: "spoken",
  },
  "VK.IE.7A.v1": {
    id: "VK.IE.7A.v1",
    dimensionId: "IE",
    subAxisId: "processingHabitat",
    variant: "A",
    version: "v1",
    phase: 2,
    promptType: "openInterpretation",
    intensity: 3,
    instructionText: "Respond with single-word adjectives or nouns ONLY.",
    modality: "text",
    stimulusRef: {
      kind: "inlineText",
      text: "Explaining before ready is...",
    },
    responseMode: "spoken",
  },
  "VK.IE.8A.v1": {
    id: "VK.IE.8A.v1",
    dimensionId: "IE",
    subAxisId: "processingHabitat",
    variant: "A",
    version: "v1",
    phase: 3,
    promptType: "microDecision",
    intensity: 3,
    instructionText: "Choose.",
    modality: "text",
    stimulusRef: {
      kind: "inlineText",
      text: "Half-formed thought: say it or hold it?",
    },
    responseMode: "spoken",
  },
  "VK.IE.9A.v1": {
    id: "VK.IE.9A.v1",
    dimensionId: "IE",
    subAxisId: "processingHabitat",
    variant: "A",
    version: "v1",
    phase: 4,
    promptType: "errorDetection",
    intensity: 4,
    instructionText: "Anything off?",
    modality: "text",
    stimulusRef: {
      kind: "inlineText",
      text: "Complex question. 'Quick thoughts only.'",
    },
    responseMode: "spoken",
  },
  "VK.IE.10A.v1": {
    id: "VK.IE.10A.v1",
    dimensionId: "IE",
    subAxisId: "processingHabitat",
    variant: "A",
    version: "v1",
    phase: 5,
    promptType: "projectionContinuation",
    isWildcard: true,
    intensity: 3,
    instructionText: "What do you do next?",
    modality: "text",
    stimulusRef: {
      kind: "inlineText",
      text: "Someone misstates what you meant.",
    },
    responseMode: "spoken",
  },

  // 3) visibilityRelationship (IDs 11–15)
  "VK.IE.11A.v1": {
    id: "VK.IE.11A.v1",
    dimensionId: "IE",
    subAxisId: "visibilityRelationship",
    variant: "A",
    version: "v1",
    phase: 1,
    promptType: "freeRecall",
    intensity: 2,
    instructionText: "What do you remember?",
    modality: "text",
    stimulusRef: {
      kind: "inlineText",
      text: "Group photo taken. You were not called.",
    },
    exposureMs: 8000,
    responseMode: "spoken",
  },
  "VK.IE.12A.v1": {
    id: "VK.IE.12A.v1",
    dimensionId: "IE",
    subAxisId: "visibilityRelationship",
    variant: "A",
    version: "v1",
    phase: 2,
    promptType: "openInterpretation",
    intensity: 3,
    instructionText: "Respond with single-word adjectives or nouns ONLY.",
    modality: "text",
    stimulusRef: {
      kind: "inlineText",
      text: "Nobody notices you.",
    },
    responseMode: "spoken",
  },
  "VK.IE.13A.v1": {
    id: "VK.IE.13A.v1",
    dimensionId: "IE",
    subAxisId: "visibilityRelationship",
    variant: "A",
    version: "v1",
    phase: 3,
    promptType: "microDecision",
    intensity: 3,
    instructionText: "Choose.",
    modality: "text",
    stimulusRef: {
      kind: "inlineText",
      text: "Be watched or be ignored?",
    },
    responseMode: "spoken",
  },
  "VK.IE.14A.v1": {
    id: "VK.IE.14A.v1",
    dimensionId: "IE",
    subAxisId: "visibilityRelationship",
    variant: "A",
    version: "v1",
    phase: 4,
    promptType: "errorDetection",
    intensity: 4,
    instructionText: "Anything off?",
    modality: "text",
    stimulusRef: {
      kind: "inlineText",
      text: "Group introduction. One person skipped.",
    },
    responseMode: "spoken",
  },
  "VK.IE.15A.v1": {
    id: "VK.IE.15A.v1",
    dimensionId: "IE",
    subAxisId: "visibilityRelationship",
    variant: "A",
    version: "v1",
    phase: 5,
    promptType: "projectionContinuation",
    isWildcard: true,
    intensity: 3,
    instructionText: "What do you do next?",
    modality: "text",
    stimulusRef: {
      kind: "inlineText",
      text: "No one notices you arrived.",
    },
    responseMode: "spoken",
  },

  // 4) connectionEconomics (IDs 16–20)
  "VK.IE.16A.v1": {
    id: "VK.IE.16A.v1",
    dimensionId: "IE",
    subAxisId: "connectionEconomics",
    variant: "A",
    version: "v1",
    phase: 1,
    promptType: "freeRecall",
    intensity: 2,
    instructionText: "What do you remember?",
    modality: "text",
    stimulusRef: {
      kind: "inlineText",
      text: "Three messages: one deep, two casual invites.",
    },
    exposureMs: 8000,
    responseMode: "spoken",
  },
  "VK.IE.17A.v1": {
    id: "VK.IE.17A.v1",
    dimensionId: "IE",
    subAxisId: "connectionEconomics",
    variant: "A",
    version: "v1",
    phase: 2,
    promptType: "openInterpretation",
    intensity: 3,
    instructionText: "Respond with single-word adjectives or nouns ONLY.",
    modality: "text",
    stimulusRef: {
      kind: "inlineText",
      text: "Being spread too thin socially is...",
    },
    responseMode: "spoken",
  },
  "VK.IE.18A.v1": {
    id: "VK.IE.18A.v1",
    dimensionId: "IE",
    subAxisId: "connectionEconomics",
    variant: "A",
    version: "v1",
    phase: 3,
    promptType: "microDecision",
    intensity: 3,
    instructionText: "Choose.",
    modality: "text",
    stimulusRef: {
      kind: "inlineText",
      text: "One deep talk or five quick chats?",
    },
    responseMode: "spoken",
  },
  "VK.IE.19A.v1": {
    id: "VK.IE.19A.v1",
    dimensionId: "IE",
    subAxisId: "connectionEconomics",
    variant: "A",
    version: "v1",
    phase: 4,
    promptType: "errorDetection",
    intensity: 4,
    instructionText: "Anything off?",
    modality: "text",
    stimulusRef: {
      kind: "inlineText",
      text: "You're told 'we're all close here.' No one knows your name.",
    },
    responseMode: "spoken",
  },
  "VK.IE.20A.v1": {
    id: "VK.IE.20A.v1",
    dimensionId: "IE",
    subAxisId: "connectionEconomics",
    variant: "A",
    version: "v1",
    phase: 5,
    promptType: "projectionContinuation",
    isWildcard: true,
    intensity: 3,
    instructionText: "What do you do next?",
    modality: "text",
    stimulusRef: {
      kind: "inlineText",
      text: "You can deepen one bond or start three more.",
    },
    responseMode: "spoken",
  },

  // 5) restorationSignature (IDs 21–25)
  "VK.IE.21A.v1": {
    id: "VK.IE.21A.v1",
    dimensionId: "IE",
    subAxisId: "restorationSignature",
    variant: "A",
    version: "v1",
    phase: 1,
    promptType: "freeRecall",
    intensity: 2,
    instructionText: "What do you remember?",
    modality: "text",
    stimulusRef: {
      kind: "inlineText",
      text: "You finally get alone time. Conversation keeps replaying.",
    },
    exposureMs: 8000,
    responseMode: "spoken",
  },
  "VK.IE.22A.v1": {
    id: "VK.IE.22A.v1",
    dimensionId: "IE",
    subAxisId: "restorationSignature",
    variant: "A",
    version: "v1",
    phase: 2,
    promptType: "openInterpretation",
    intensity: 3,
    instructionText: "Respond with single-word adjectives or nouns ONLY.",
    modality: "text",
    stimulusRef: {
      kind: "inlineText",
      text: "Alone but not restored is...",
    },
    responseMode: "spoken",
  },
  "VK.IE.23A.v1": {
    id: "VK.IE.23A.v1",
    dimensionId: "IE",
    subAxisId: "restorationSignature",
    variant: "A",
    version: "v1",
    phase: 3,
    promptType: "microDecision",
    intensity: 3,
    instructionText: "Choose.",
    modality: "text",
    stimulusRef: {
      kind: "inlineText",
      text: "Depleted: close the door or call someone?",
    },
    responseMode: "spoken",
  },
  "VK.IE.24A.v1": {
    id: "VK.IE.24A.v1",
    dimensionId: "IE",
    subAxisId: "restorationSignature",
    variant: "A",
    version: "v1",
    phase: 4,
    promptType: "errorDetection",
    intensity: 4,
    instructionText: "Anything off?",
    modality: "text",
    stimulusRef: {
      kind: "inlineText",
      text: "Recovery time scheduled. Group debrief added.",
    },
    responseMode: "spoken",
  },
  "VK.IE.25A.v1": {
    id: "VK.IE.25A.v1",
    dimensionId: "IE",
    subAxisId: "restorationSignature",
    variant: "A",
    version: "v1",
    phase: 5,
    promptType: "projectionContinuation",
    isWildcard: true,
    intensity: 3,
    instructionText: "What do you do next?",
    modality: "text",
    stimulusRef: {
      kind: "inlineText",
      text: "You withdraw, but the interaction follows you.",
    },
    responseMode: "spoken",
  },


  // ==========================
  // NS — KnowledgeApproachAxis
  // (lowLabel is N-leaning)
  // ==========================

  // 1) attentionPlane (IDs 1–5)
  "VK.NS.1A.v1": {
    id: "VK.NS.1A.v1",
    dimensionId: "NS",
    subAxisId: "attentionPlane",
    variant: "A",
    version: "v1",
    phase: 1,
    promptType: "freeRecall",
    intensity: 2,
    instructionText: "What do you remember?",
    modality: "text",
    stimulusRef: {
      kind: "inlineText",
      text: "You just skimmed a collage mixing satellite maps, handwritten checklists, and concept sketches. What details do you remember grabbing your attention first?",
    },
    exposureMs: 8000,
    responseMode: "spoken",
  },
  "VK.NS.2A.v1": {
    id: "VK.NS.2A.v1",
    dimensionId: "NS",
    subAxisId: "attentionPlane",
    variant: "A",
    version: "v1",
    phase: 2,
    promptType: "openInterpretation",
    intensity: 3,
    instructionText: "What do you think is happening here?",
    modality: "text",
    stimulusRef: {
      kind: "inlineText",
      text: "A short video shows someone staring at traffic lights while sketching constellations in the margins. What do you think is happening on their attention plane?",
    },
    responseMode: "spoken",
  },
  "VK.NS.3A.v1": {
    id: "VK.NS.3A.v1",
    dimensionId: "NS",
    subAxisId: "attentionPlane",
    variant: "A",
    version: "v1",
    phase: 3,
    promptType: "microDecision",
    intensity: 3,
    instructionText: "What would you do?",
    modality: "text",
    stimulusRef: {
      kind: "inlineText",
      text: "A critical issue surfaces: you can dive straight into raw log files or step back to redraw the broader system pattern first. What do you do?",
    },
    responseMode: "spoken",
  },
  "VK.NS.4A.v1": {
    id: "VK.NS.4A.v1",
    dimensionId: "NS",
    subAxisId: "attentionPlane",
    variant: "A",
    version: "v1",
    phase: 4,
    promptType: "errorDetection",
    intensity: 4,
    instructionText: "Does anything seem off?",
    modality: "text",
    stimulusRef: {
      kind: "inlineText",
      text: "You read a report that jumps from poetic themes to precise metrics with no bridge. Does anything seem off?",
    },
    responseMode: "spoken",
  },
  "VK.NS.5A.v1": {
    id: "VK.NS.5A.v1",
    dimensionId: "NS",
    subAxisId: "attentionPlane",
    variant: "A",
    version: "v1",
    phase: 5,
    promptType: "projectionContinuation",
    isWildcard: true,
    intensity: 3,
    instructionText: "What happens next?",
    modality: "text",
    stimulusRef: {
      kind: "inlineText",
      text: "Your team hands you both a drone photo and a street-level snapshot of the same site. What happens next in how you extend the story?",
    },
    responseMode: "spoken",
  },

  // 2) temporalHabitat (IDs 6–10)
  "VK.NS.6A.v1": {
    id: "VK.NS.6A.v1",
    dimensionId: "NS",
    subAxisId: "temporalHabitat",
    variant: "A",
    version: "v1",
    phase: 1,
    promptType: "freeRecall",
    intensity: 2,
    instructionText: "What do you remember?",
    modality: "text",
    stimulusRef: {
      kind: "inlineText",
      text: "You just skimmed three sticky notes—a childhood snapshot, today's emergency list, and a sketch of next year's launch. What details do you remember grabbing you?",
    },
    exposureMs: 8000,
    responseMode: "spoken",
  },
  "VK.NS.7A.v1": {
    id: "VK.NS.7A.v1",
    dimensionId: "NS",
    subAxisId: "temporalHabitat",
    variant: "A",
    version: "v1",
    phase: 2,
    promptType: "openInterpretation",
    intensity: 3,
    instructionText: "What do you think is happening here?",
    modality: "text",
    stimulusRef: {
      kind: "inlineText",
      text: "A clip shows someone narrating a five-year roadmap while burning dinner on the stove. What do you think that says about their temporal habitat?",
    },
    responseMode: "spoken",
  },
  "VK.NS.8A.v1": {
    id: "VK.NS.8A.v1",
    dimensionId: "NS",
    subAxisId: "temporalHabitat",
    variant: "A",
    version: "v1",
    phase: 3,
    promptType: "microDecision",
    intensity: 3,
    instructionText: "What would you do?",
    modality: "text",
    stimulusRef: {
      kind: "inlineText",
      text: "You can spend the next hour clearing an urgent ticket or drafting the long-range roadmap everyone keeps deferring. What do you do?",
    },
    responseMode: "spoken",
  },
  "VK.NS.9A.v1": {
    id: "VK.NS.9A.v1",
    dimensionId: "NS",
    subAxisId: "temporalHabitat",
    variant: "A",
    version: "v1",
    phase: 4,
    promptType: "errorDetection",
    intensity: 4,
    instructionText: "Does anything seem off?",
    modality: "text",
    stimulusRef: {
      kind: "inlineText",
      text: "A sprint board shows future milestones obsessively detailed but today's tasks half empty. Does anything seem off?",
    },
    responseMode: "spoken",
  },
  "VK.NS.10A.v1": {
    id: "VK.NS.10A.v1",
    dimensionId: "NS",
    subAxisId: "temporalHabitat",
    variant: "A",
    version: "v1",
    phase: 5,
    promptType: "projectionContinuation",
    isWildcard: true,
    intensity: 3,
    instructionText: "What happens next?",
    modality: "text",
    stimulusRef: {
      kind: "inlineText",
      text: "You're midway through recording a message to your future self when a present-day crisis alert pings. What happens next?",
    },
    responseMode: "spoken",
  },

  // 3) informationDiet (IDs 11–15)
  "VK.NS.11A.v1": {
    id: "VK.NS.11A.v1",
    dimensionId: "NS",
    subAxisId: "informationDiet",
    variant: "A",
    version: "v1",
    phase: 1,
    promptType: "freeRecall",
    intensity: 2,
    instructionText: "What do you remember?",
    modality: "text",
    stimulusRef: {
      kind: "inlineText",
      text: "You just scrolled a feed that alternated raw meeting transcripts with tight executive summaries. What details do you remember latching onto?",
    },
    exposureMs: 8000,
    responseMode: "spoken",
  },
  "VK.NS.12A.v1": {
    id: "VK.NS.12A.v1",
    dimensionId: "NS",
    subAxisId: "informationDiet",
    variant: "A",
    version: "v1",
    phase: 2,
    promptType: "openInterpretation",
    intensity: 3,
    instructionText: "What do you think is happening here?",
    modality: "text",
    stimulusRef: {
      kind: "inlineText",
      text: "A researcher listens to chaotic field audio while bookmarking only one clean chart. What do you think is happening with their information diet?",
    },
    responseMode: "spoken",
  },
  "VK.NS.13A.v1": {
    id: "VK.NS.13A.v1",
    dimensionId: "NS",
    subAxisId: "informationDiet",
    variant: "A",
    version: "v1",
    phase: 3,
    promptType: "microDecision",
    intensity: 3,
    instructionText: "What would you do?",
    modality: "text",
    stimulusRef: {
      kind: "inlineText",
      text: "You can read a forty-page primary study tonight or wait for a trusted teammate's digest tomorrow. What do you do?",
    },
    responseMode: "spoken",
  },
  "VK.NS.14A.v1": {
    id: "VK.NS.14A.v1",
    dimensionId: "NS",
    subAxisId: "informationDiet",
    variant: "A",
    version: "v1",
    phase: 4,
    promptType: "errorDetection",
    intensity: 4,
    instructionText: "Does anything seem off?",
    modality: "text",
    stimulusRef: {
      kind: "inlineText",
      text: "A briefing packet is stuffed with sensational screenshots but cites no sources. Does anything seem off?",
    },
    responseMode: "spoken",
  },
  "VK.NS.15A.v1": {
    id: "VK.NS.15A.v1",
    dimensionId: "NS",
    subAxisId: "informationDiet",
    variant: "A",
    version: "v1",
    phase: 5,
    promptType: "projectionContinuation",
    isWildcard: true,
    intensity: 3,
    instructionText: "What happens next?",
    modality: "text",
    stimulusRef: {
      kind: "inlineText",
      text: "You're midway through curating tomorrow's reading queue when someone drops a raw data dump link. How do you continue?",
    },
    responseMode: "spoken",
  },

  // 4) realityRelationship (IDs 16–20)
  "VK.NS.16A.v1": {
    id: "VK.NS.16A.v1",
    dimensionId: "NS",
    subAxisId: "realityRelationship",
    variant: "A",
    version: "v1",
    phase: 1,
    promptType: "freeRecall",
    intensity: 2,
    instructionText: "What do you remember?",
    modality: "text",
    stimulusRef: {
      kind: "inlineText",
      text: "You read two short passages—one strict lab log, one vivid imagination sketch. What details do you remember about how each landed?",
    },
    exposureMs: 8000,
    responseMode: "spoken",
  },
  "VK.NS.17A.v1": {
    id: "VK.NS.17A.v1",
    dimensionId: "NS",
    subAxisId: "realityRelationship",
    variant: "A",
    version: "v1",
    phase: 2,
    promptType: "openInterpretation",
    intensity: 3,
    instructionText: "What do you think is happening here?",
    modality: "text",
    stimulusRef: {
      kind: "inlineText",
      text: "A designer overlays glowing fantasy city lights onto a real satellite photo. What do you think is happening in their reality relationship?",
    },
    responseMode: "spoken",
  },
  "VK.NS.18A.v1": {
    id: "VK.NS.18A.v1",
    dimensionId: "NS",
    subAxisId: "realityRelationship",
    variant: "A",
    version: "v1",
    phase: 3,
    promptType: "microDecision",
    intensity: 3,
    instructionText: "What would you do?",
    modality: "text",
    stimulusRef: {
      kind: "inlineText",
      text: "Tomorrow's pitch can feature a cinematic narrative first or a round of real-user verification. Which do you choose?",
    },
    responseMode: "spoken",
  },
  "VK.NS.19A.v1": {
    id: "VK.NS.19A.v1",
    dimensionId: "NS",
    subAxisId: "realityRelationship",
    variant: "A",
    version: "v1",
    phase: 4,
    promptType: "errorDetection",
    intensity: 4,
    instructionText: "Does anything seem off?",
    modality: "text",
    stimulusRef: {
      kind: "inlineText",
      text: "A product deck promises guaranteed transformation but never references real data. Does anything seem off?",
    },
    responseMode: "spoken",
  },
  "VK.NS.20A.v1": {
    id: "VK.NS.20A.v1",
    dimensionId: "NS",
    subAxisId: "realityRelationship",
    variant: "A",
    version: "v1",
    phase: 5,
    promptType: "projectionContinuation",
    isWildcard: true,
    intensity: 3,
    instructionText: "What happens next?",
    modality: "text",
    stimulusRef: {
      kind: "inlineText",
      text: "Mid-prototype you notice the story drifting away from what users actually said. How do you continue?",
    },
    responseMode: "spoken",
  },

  // 5) meaningThreshold (IDs 21–25)
  "VK.NS.21A.v1": {
    id: "VK.NS.21A.v1",
    dimensionId: "NS",
    subAxisId: "meaningThreshold",
    variant: "A",
    version: "v1",
    phase: 1,
    promptType: "freeRecall",
    intensity: 2,
    instructionText: "What do you remember?",
    modality: "text",
    stimulusRef: {
      kind: "inlineText",
      text: "You skimmed notes from a tight budget review and from a mission workshop. What details do you remember about what actually mattered to you?",
    },
    exposureMs: 8000,
    responseMode: "spoken",
  },
  "VK.NS.22A.v1": {
    id: "VK.NS.22A.v1",
    dimensionId: "NS",
    subAxisId: "meaningThreshold",
    variant: "A",
    version: "v1",
    phase: 2,
    promptType: "openInterpretation",
    intensity: 3,
    instructionText: "What do you think is happening here?",
    modality: "text",
    stimulusRef: {
      kind: "inlineText",
      text: "A clip shows someone turning a simple chore into a ritual while another person checks the box without looking up. What do you think this reveals about their meaning thresholds?",
    },
    responseMode: "spoken",
  },
  "VK.NS.23A.v1": {
    id: "VK.NS.23A.v1",
    dimensionId: "NS",
    subAxisId: "meaningThreshold",
    variant: "A",
    version: "v1",
    phase: 3,
    promptType: "microDecision",
    intensity: 3,
    instructionText: "What would you do?",
    modality: "text",
    stimulusRef: {
      kind: "inlineText",
      text: "You can accept a lucrative assignment that feels hollow or a messy project that clearly matters to people. What do you do?",
    },
    responseMode: "spoken",
  },
  "VK.NS.24A.v1": {
    id: "VK.NS.24A.v1",
    dimensionId: "NS",
    subAxisId: "meaningThreshold",
    variant: "A",
    version: "v1",
    phase: 4,
    promptType: "errorDetection",
    intensity: 4,
    instructionText: "Does anything seem off?",
    modality: "text",
    stimulusRef: {
      kind: "inlineText",
      text: "A task list is packed with deliverables but never states why they exist. Does anything seem off?",
    },
    responseMode: "spoken",
  },
  "VK.NS.25A.v1": {
    id: "VK.NS.25A.v1",
    dimensionId: "NS",
    subAxisId: "meaningThreshold",
    variant: "A",
    version: "v1",
    phase: 5,
    promptType: "projectionContinuation",
    isWildcard: true,
    intensity: 3,
    instructionText: "What happens next?",
    modality: "text",
    stimulusRef: {
      kind: "inlineText",
      text: "You finish a flawless rollout that somehow feels empty. What happens next to make it matter?",
    },
    responseMode: "spoken",
  },


  // ======================
  // TF — DecisionStyleAxis
  // ======================

  // 1) evaluationReflex (IDs 1–5)
  "VK.TF.1A.v1": {
    id: "VK.TF.1A.v1",
    dimensionId: "TF",
    subAxisId: "evaluationReflex",
    variant: "A",
    version: "v1",
    phase: 1,
    promptType: "freeRecall",
    intensity: 2,
    instructionText: "What do you remember?",
    modality: "text",
    stimulusRef: {
      kind: "inlineText",
      text: "You skimmed two decision memos: one opens with a gut feeling, the other with stacked evidence. What details do you remember noticing first?",
    },
    exposureMs: 8000,
    responseMode: "spoken",
  },
  "VK.TF.2A.v1": {
    id: "VK.TF.2A.v1",
    dimensionId: "TF",
    subAxisId: "evaluationReflex",
    variant: "A",
    version: "v1",
    phase: 2,
    promptType: "openInterpretation",
    intensity: 3,
    instructionText: "What do you think is happening here?",
    modality: "text",
    stimulusRef: {
      kind: "inlineText",
      text: "A leader pauses mid-meeting, weighing a teammate's emotion against the spreadsheet on the wall. What do you think is happening in their evaluation reflex?",
    },
    responseMode: "spoken",
  },
  "VK.TF.3A.v1": {
    id: "VK.TF.3A.v1",
    dimensionId: "TF",
    subAxisId: "evaluationReflex",
    variant: "A",
    version: "v1",
    phase: 3,
    promptType: "microDecision",
    intensity: 3,
    instructionText: "What would you do?",
    modality: "text",
    stimulusRef: {
      kind: "inlineText",
      text: "A vote is leaning toward an option you believe the data contradicts. Do you surface the evidence now or defer to the room's feeling?",
    },
    responseMode: "spoken",
  },
  "VK.TF.4A.v1": {
    id: "VK.TF.4A.v1",
    dimensionId: "TF",
    subAxisId: "evaluationReflex",
    variant: "A",
    version: "v1",
    phase: 4,
    promptType: "errorDetection",
    intensity: 4,
    instructionText: "Does anything seem off?",
    modality: "text",
    stimulusRef: {
      kind: "inlineText",
      text: "A proposal appeals to \"what feels right\" but never shows a baseline. Does anything seem off?",
    },
    responseMode: "spoken",
  },
  "VK.TF.5A.v1": {
    id: "VK.TF.5A.v1",
    dimensionId: "TF",
    subAxisId: "evaluationReflex",
    variant: "A",
    version: "v1",
    phase: 5,
    promptType: "projectionContinuation",
    isWildcard: true,
    intensity: 3,
    instructionText: "What happens next?",
    modality: "text",
    stimulusRef: {
      kind: "inlineText",
      text: "Halfway through a review someone demands your gut verdict before the analysis is done. What happens next?",
    },
    responseMode: "spoken",
  },

  // 2) truthOrientation (IDs 6–10)
  "VK.TF.6A.v1": {
    id: "VK.TF.6A.v1",
    dimensionId: "TF",
    subAxisId: "truthOrientation",
    variant: "A",
    version: "v1",
    phase: 1,
    promptType: "freeRecall",
    intensity: 2,
    instructionText: "What do you remember?",
    modality: "text",
    stimulusRef: {
      kind: "inlineText",
      text: "You just read two statements about the same event—one sugarcoated, one blunt. What details do you remember reacting to?",
    },
    exposureMs: 8000,
    responseMode: "spoken",
  },
  "VK.TF.7A.v1": {
    id: "VK.TF.7A.v1",
    dimensionId: "TF",
    subAxisId: "truthOrientation",
    variant: "A",
    version: "v1",
    phase: 2,
    promptType: "openInterpretation",
    intensity: 3,
    instructionText: "What do you think is happening here?",
    modality: "text",
    stimulusRef: {
      kind: "inlineText",
      text: "A researcher proudly circles a conclusion, then quietly erases it after spotting new evidence. What do you think this says about their truth orientation?",
    },
    responseMode: "spoken",
  },
  "VK.TF.8A.v1": {
    id: "VK.TF.8A.v1",
    dimensionId: "TF",
    subAxisId: "truthOrientation",
    variant: "A",
    version: "v1",
    phase: 3,
    promptType: "microDecision",
    intensity: 3,
    instructionText: "What would you do?",
    modality: "text",
    stimulusRef: {
      kind: "inlineText",
      text: "Your team asks you to soften a finding so a client won't panic. Do you adjust the wording or deliver it as-is?",
    },
    responseMode: "spoken",
  },
  "VK.TF.9A.v1": {
    id: "VK.TF.9A.v1",
    dimensionId: "TF",
    subAxisId: "truthOrientation",
    variant: "A",
    version: "v1",
    phase: 4,
    promptType: "errorDetection",
    intensity: 4,
    instructionText: "Does anything seem off?",
    modality: "text",
    stimulusRef: {
      kind: "inlineText",
      text: "A dashboard screenshot skips the one metric that contradicts the story. Does anything seem off?",
    },
    responseMode: "spoken",
  },
  "VK.TF.10A.v1": {
    id: "VK.TF.10A.v1",
    dimensionId: "TF",
    subAxisId: "truthOrientation",
    variant: "A",
    version: "v1",
    phase: 5,
    promptType: "projectionContinuation",
    isWildcard: true,
    intensity: 3,
    instructionText: "What happens next?",
    modality: "text",
    stimulusRef: {
      kind: "inlineText",
      text: "Mid-interview someone presses you about a stubborn fact that won't go away. How do you continue?",
    },
    responseMode: "spoken",
  },

  // 3) decisionSubstrate (IDs 11–15)
  "VK.TF.11A.v1": {
    id: "VK.TF.11A.v1",
    dimensionId: "TF",
    subAxisId: "decisionSubstrate",
    variant: "A",
    version: "v1",
    phase: 1,
    promptType: "freeRecall",
    intensity: 2,
    instructionText: "What do you remember?",
    modality: "text",
    stimulusRef: {
      kind: "inlineText",
      text: "You just looked at artifacts from your last three big calls—one spreadsheet, one rambling voice memo, one gut note. What details do you remember about how you decided?",
    },
    exposureMs: 8000,
    responseMode: "spoken",
  },
  "VK.TF.12A.v1": {
    id: "VK.TF.12A.v1",
    dimensionId: "TF",
    subAxisId: "decisionSubstrate",
    variant: "A",
    version: "v1",
    phase: 2,
    promptType: "openInterpretation",
    intensity: 3,
    instructionText: "What do you think is happening here?",
    modality: "text",
    stimulusRef: {
      kind: "inlineText",
      text: "A founder keeps flipping between touching a physical prototype and scanning a finance sheet. What does that tell you about their decision substrate?",
    },
    responseMode: "spoken",
  },
  "VK.TF.13A.v1": {
    id: "VK.TF.13A.v1",
    dimensionId: "TF",
    subAxisId: "decisionSubstrate",
    variant: "A",
    version: "v1",
    phase: 3,
    promptType: "microDecision",
    intensity: 3,
    instructionText: "What would you do?",
    modality: "text",
    stimulusRef: {
      kind: "inlineText",
      text: "To unblock a project you can sketch with a teammate on a whiteboard or draft a detailed solo spec. What do you choose?",
    },
    responseMode: "spoken",
  },
  "VK.TF.14A.v1": {
    id: "VK.TF.14A.v1",
    dimensionId: "TF",
    subAxisId: "decisionSubstrate",
    variant: "A",
    version: "v1",
    phase: 4,
    promptType: "errorDetection",
    intensity: 4,
    instructionText: "Does anything seem off?",
    modality: "text",
    stimulusRef: {
      kind: "inlineText",
      text: "A launch plan references \"gut sense\" repeatedly but never records assumptions. Does anything seem off?",
    },
    responseMode: "spoken",
  },
  "VK.TF.15A.v1": {
    id: "VK.TF.15A.v1",
    dimensionId: "TF",
    subAxisId: "decisionSubstrate",
    variant: "A",
    version: "v1",
    phase: 5,
    promptType: "projectionContinuation",
    isWildcard: true,
    intensity: 3,
    instructionText: "What happens next?",
    modality: "text",
    stimulusRef: {
      kind: "inlineText",
      text: "You're surrounded by sticky notes and sensor readouts halfway through a call. What do you add next to move the decision forward?",
    },
    responseMode: "spoken",
  },

  // 4) conflictMetabolism (IDs 16–20)
  "VK.TF.16A.v1": {
    id: "VK.TF.16A.v1",
    dimensionId: "TF",
    subAxisId: "conflictMetabolism",
    variant: "A",
    version: "v1",
    phase: 1,
    promptType: "freeRecall",
    intensity: 2,
    instructionText: "What do you remember?",
    modality: "text",
    stimulusRef: {
      kind: "inlineText",
      text: "You reread a short transcript from your last disagreement. What details do you remember noticing first?",
    },
    exposureMs: 8000,
    responseMode: "spoken",
  },
  "VK.TF.17A.v1": {
    id: "VK.TF.17A.v1",
    dimensionId: "TF",
    subAxisId: "conflictMetabolism",
    variant: "A",
    version: "v1",
    phase: 2,
    promptType: "openInterpretation",
    intensity: 3,
    instructionText: "What do you think is happening here?",
    modality: "text",
    stimulusRef: {
      kind: "inlineText",
      text: "A clip shows one person leaning forward into the table while another folds their arms and smiles tightly. What do you think is happening with their conflict metabolism?",
    },
    responseMode: "spoken",
  },
  "VK.TF.18A.v1": {
    id: "VK.TF.18A.v1",
    dimensionId: "TF",
    subAxisId: "conflictMetabolism",
    variant: "A",
    version: "v1",
    phase: 3,
    promptType: "microDecision",
    intensity: 3,
    instructionText: "What would you do?",
    modality: "text",
    stimulusRef: {
      kind: "inlineText",
      text: "A teammate fires off a sharp message. Do you respond now with your stance or wait until tomorrow?",
    },
    responseMode: "spoken",
  },
  "VK.TF.19A.v1": {
    id: "VK.TF.19A.v1",
    dimensionId: "TF",
    subAxisId: "conflictMetabolism",
    variant: "A",
    version: "v1",
    phase: 4,
    promptType: "errorDetection",
    intensity: 4,
    instructionText: "Does anything seem off?",
    modality: "text",
    stimulusRef: {
      kind: "inlineText",
      text: "A retrospective deck lists action items but never names the tension everyone felt. Does anything seem off?",
    },
    responseMode: "spoken",
  },
  "VK.TF.20A.v1": {
    id: "VK.TF.20A.v1",
    dimensionId: "TF",
    subAxisId: "conflictMetabolism",
    variant: "A",
    version: "v1",
    phase: 5,
    promptType: "projectionContinuation",
    isWildcard: true,
    intensity: 3,
    instructionText: "What happens next?",
    modality: "text",
    stimulusRef: {
      kind: "inlineText",
      text: "Mid-confrontation the room goes quiet and everyone looks at you. What happens next?",
    },
    responseMode: "spoken",
  },

  // 5) boundaryArchitecture (IDs 21–25)
  "VK.TF.21A.v1": {
    id: "VK.TF.21A.v1",
    dimensionId: "TF",
    subAxisId: "boundaryArchitecture",
    variant: "A",
    version: "v1",
    phase: 1,
    promptType: "freeRecall",
    intensity: 2,
    instructionText: "What do you remember?",
    modality: "text",
    stimulusRef: {
      kind: "inlineText",
      text: "You just reread three quick requests where someone asked for more of you. What details do you remember about how you responded?",
    },
    exposureMs: 8000,
    responseMode: "spoken",
  },
  "VK.TF.22A.v1": {
    id: "VK.TF.22A.v1",
    dimensionId: "TF",
    subAxisId: "boundaryArchitecture",
    variant: "A",
    version: "v1",
    phase: 2,
    promptType: "openInterpretation",
    intensity: 3,
    instructionText: "What do you think is happening here?",
    modality: "text",
    stimulusRef: {
      kind: "inlineText",
      text: "A clip shows someone smiling while sliding their chair back as coworkers reach for their laptop. What do you think is happening with their boundary architecture?",
    },
    responseMode: "spoken",
  },
  "VK.TF.23A.v1": {
    id: "VK.TF.23A.v1",
    dimensionId: "TF",
    subAxisId: "boundaryArchitecture",
    variant: "A",
    version: "v1",
    phase: 3,
    promptType: "microDecision",
    intensity: 3,
    instructionText: "What would you do?",
    modality: "text",
    stimulusRef: {
      kind: "inlineText",
      text: "A client adds weekend work after scope creep. Do you draw a line or take it on?",
    },
    responseMode: "spoken",
  },
  "VK.TF.24A.v1": {
    id: "VK.TF.24A.v1",
    dimensionId: "TF",
    subAxisId: "boundaryArchitecture",
    variant: "A",
    version: "v1",
    phase: 4,
    promptType: "errorDetection",
    intensity: 4,
    instructionText: "Does anything seem off?",
    modality: "text",
    stimulusRef: {
      kind: "inlineText",
      text: "A team plan advertises \"open door anytime\" while expecting deep focus output. Does anything seem off?",
    },
    responseMode: "spoken",
  },
  "VK.TF.25A.v1": {
    id: "VK.TF.25A.v1",
    dimensionId: "TF",
    subAxisId: "boundaryArchitecture",
    variant: "A",
    version: "v1",
    phase: 5,
    promptType: "projectionContinuation",
    isWildcard: true,
    intensity: 3,
    instructionText: "What happens next?",
    modality: "text",
    stimulusRef: {
      kind: "inlineText",
      text: "Mid-call a partner stacks a new favor on top of an old one. How does the scene continue?",
    },
    responseMode: "spoken",
  },


  // ======================
  // JP — ActionStrategyAxis
  // ======================

  // 1) closureDrive (IDs 1–5)
  "VK.JP.1A.v1": {
    id: "VK.JP.1A.v1",
    dimensionId: "JP",
    subAxisId: "closureDrive",
    variant: "A",
    version: "v1",
    phase: 1,
    promptType: "freeRecall",
    intensity: 2,
    instructionText: "What do you remember?",
    modality: "text",
    stimulusRef: {
      kind: "inlineText",
      text: "You just scanned your task board showing five open loops and two freshly closed ones. What details do you remember about the unfinished pieces?",
    },
    exposureMs: 8000,
    responseMode: "spoken",
  },
  "VK.JP.2A.v1": {
    id: "VK.JP.2A.v1",
    dimensionId: "JP",
    subAxisId: "closureDrive",
    variant: "A",
    version: "v1",
    phase: 2,
    promptType: "openInterpretation",
    intensity: 3,
    instructionText: "What do you think is happening here?",
    modality: "text",
    stimulusRef: {
      kind: "inlineText",
      text: "A short clip shows one person re-checking locked doors while another leaves every cabinet open. What does that tell you about their closure drives?",
    },
    responseMode: "spoken",
  },
  "VK.JP.3A.v1": {
    id: "VK.JP.3A.v1",
    dimensionId: "JP",
    subAxisId: "closureDrive",
    variant: "A",
    version: "v1",
    phase: 3,
    promptType: "microDecision",
    intensity: 3,
    instructionText: "What would you do?",
    modality: "text",
    stimulusRef: {
      kind: "inlineText",
      text: "A partner asks whether to send a draft now for closure or hold it another day for polish. What do you do?",
    },
    responseMode: "spoken",
  },
  "VK.JP.4A.v1": {
    id: "VK.JP.4A.v1",
    dimensionId: "JP",
    subAxisId: "closureDrive",
    variant: "A",
    version: "v1",
    phase: 4,
    promptType: "errorDetection",
    intensity: 4,
    instructionText: "Does anything seem off?",
    modality: "text",
    stimulusRef: {
      kind: "inlineText",
      text: "A project tracker shows dozens of \"in progress\" cards with no owners. Does anything seem off?",
    },
    responseMode: "spoken",
  },
  "VK.JP.5A.v1": {
    id: "VK.JP.5A.v1",
    dimensionId: "JP",
    subAxisId: "closureDrive",
    variant: "A",
    version: "v1",
    phase: 5,
    promptType: "projectionContinuation",
    isWildcard: true,
    intensity: 3,
    instructionText: "What happens next?",
    modality: "text",
    stimulusRef: {
      kind: "inlineText",
      text: "You're halfway through zeroing your inbox when a major new thread arrives. What happens next?",
    },
    responseMode: "spoken",
  },

  // 2) structureRelationship (IDs 6–10)
  "VK.JP.6A.v1": {
    id: "VK.JP.6A.v1",
    dimensionId: "JP",
    subAxisId: "structureRelationship",
    variant: "A",
    version: "v1",
    phase: 1,
    promptType: "freeRecall",
    intensity: 2,
    instructionText: "What do you remember?",
    modality: "text",
    stimulusRef: {
      kind: "inlineText",
      text: "You just compared yesterday's color-coded schedule with today's blank canvas. What details do you remember about how you reacted?",
    },
    exposureMs: 8000,
    responseMode: "spoken",
  },
  "VK.JP.7A.v1": {
    id: "VK.JP.7A.v1",
    dimensionId: "JP",
    subAxisId: "structureRelationship",
    variant: "A",
    version: "v1",
    phase: 2,
    promptType: "openInterpretation",
    intensity: 3,
    instructionText: "What do you think is happening here?",
    modality: "text",
    stimulusRef: {
      kind: "inlineText",
      text: "A video shows one person relaxing only after lining notebooks into a grid while another thrives in piles. What do you make of their structure relationships?",
    },
    responseMode: "spoken",
  },
  "VK.JP.8A.v1": {
    id: "VK.JP.8A.v1",
    dimensionId: "JP",
    subAxisId: "structureRelationship",
    variant: "A",
    version: "v1",
    phase: 3,
    promptType: "microDecision",
    intensity: 3,
    instructionText: "What would you do?",
    modality: "text",
    stimulusRef: {
      kind: "inlineText",
      text: "Minutes before kickoff the team suggests ditching the agenda to \"feel it out.\" Do you go along or hold the plan?",
    },
    responseMode: "spoken",
  },
  "VK.JP.9A.v1": {
    id: "VK.JP.9A.v1",
    dimensionId: "JP",
    subAxisId: "structureRelationship",
    variant: "A",
    version: "v1",
    phase: 4,
    promptType: "errorDetection",
    intensity: 4,
    instructionText: "Does anything seem off?",
    modality: "text",
    stimulusRef: {
      kind: "inlineText",
      text: "A project outline mixes hourly checkpoints with an instruction to \"keep it loose.\" Does anything seem off?",
    },
    responseMode: "spoken",
  },
  "VK.JP.10A.v1": {
    id: "VK.JP.10A.v1",
    dimensionId: "JP",
    subAxisId: "structureRelationship",
    variant: "A",
    version: "v1",
    phase: 5,
    promptType: "projectionContinuation",
    isWildcard: true,
    intensity: 3,
    instructionText: "What happens next?",
    modality: "text",
    stimulusRef: {
      kind: "inlineText",
      text: "You're halfway through redesigning your workspace system when a surprise change hits. How do you continue building structure?",
    },
    responseMode: "spoken",
  },

  // 3) commitmentMetabolism (IDs 11–15)
  "VK.JP.11A.v1": {
    id: "VK.JP.11A.v1",
    dimensionId: "JP",
    subAxisId: "commitmentMetabolism",
    variant: "A",
    version: "v1",
    phase: 1,
    promptType: "freeRecall",
    intensity: 2,
    instructionText: "What do you remember?",
    modality: "text",
    stimulusRef: {
      kind: "inlineText",
      text: "You just reviewed every commitment you made this month—some stuck, some dissolved. What stood out to you?",
    },
    exposureMs: 8000,
    responseMode: "spoken",
  },
  "VK.JP.12A.v1": {
    id: "VK.JP.12A.v1",
    dimensionId: "JP",
    subAxisId: "commitmentMetabolism",
    variant: "A",
    version: "v1",
    phase: 2,
    promptType: "openInterpretation",
    intensity: 3,
    instructionText: "What do you think is happening here?",
    modality: "text",
    stimulusRef: {
      kind: "inlineText",
      text: "A clip shows one person glowing the moment they sign up while another shrinks as soon as they say yes. What does that reveal about their commitment metabolism?",
    },
    responseMode: "spoken",
  },
  "VK.JP.13A.v1": {
    id: "VK.JP.13A.v1",
    dimensionId: "JP",
    subAxisId: "commitmentMetabolism",
    variant: "A",
    version: "v1",
    phase: 3,
    promptType: "microDecision",
    intensity: 3,
    instructionText: "What would you do?",
    modality: "text",
    stimulusRef: {
      kind: "inlineText",
      text: "A dream collaboration needs your yes tonight even though you are at capacity. Do you commit or hold off?",
    },
    responseMode: "spoken",
  },
  "VK.JP.14A.v1": {
    id: "VK.JP.14A.v1",
    dimensionId: "JP",
    subAxisId: "commitmentMetabolism",
    variant: "A",
    version: "v1",
    phase: 4,
    promptType: "errorDetection",
    intensity: 4,
    instructionText: "Does anything seem off?",
    modality: "text",
    stimulusRef: {
      kind: "inlineText",
      text: "A timeline shows overlapping promises with no exit ramps. Does anything seem off?",
    },
    responseMode: "spoken",
  },
  "VK.JP.15A.v1": {
    id: "VK.JP.15A.v1",
    dimensionId: "JP",
    subAxisId: "commitmentMetabolism",
    variant: "A",
    version: "v1",
    phase: 5,
    promptType: "projectionContinuation",
    isWildcard: true,
    intensity: 3,
    instructionText: "What happens next?",
    modality: "text",
    stimulusRef: {
      kind: "inlineText",
      text: "You're midway through renegotiating a contract when the other side asks for a bigger pledge. How do you continue?",
    },
    responseMode: "spoken",
  },

  // 4) temporalOrientationToPlans (IDs 16–20)
  "VK.JP.16A.v1": {
    id: "VK.JP.16A.v1",
    dimensionId: "JP",
    subAxisId: "temporalOrientationToPlans",
    variant: "A",
    version: "v1",
    phase: 1,
    promptType: "freeRecall",
    intensity: 2,
    instructionText: "What do you remember?",
    modality: "text",
    stimulusRef: {
      kind: "inlineText",
      text: "You just skimmed a roadmap showing deadlines for today, next month, and next year. What details do you remember about where your attention stuck?",
    },
    exposureMs: 8000,
    responseMode: "spoken",
  },
  "VK.JP.17A.v1": {
    id: "VK.JP.17A.v1",
    dimensionId: "JP",
    subAxisId: "temporalOrientationToPlans",
    variant: "A",
    version: "v1",
    phase: 2,
    promptType: "openInterpretation",
    intensity: 3,
    instructionText: "What do you think is happening here?",
    modality: "text",
    stimulusRef: {
      kind: "inlineText",
      text: "A video shows one teammate labeling every milestone and another scribbling \"we'll see\" across the same board. What does that say about their temporal orientation to plans?",
    },
    responseMode: "spoken",
  },
  "VK.JP.18A.v1": {
    id: "VK.JP.18A.v1",
    dimensionId: "JP",
    subAxisId: "temporalOrientationToPlans",
    variant: "A",
    version: "v1",
    phase: 3,
    promptType: "microDecision",
    intensity: 3,
    instructionText: "What would you do?",
    modality: "text",
    stimulusRef: {
      kind: "inlineText",
      text: "A venue needs to be booked six months ahead while a better option might appear later. What do you do?",
    },
    responseMode: "spoken",
  },
  "VK.JP.19A.v1": {
    id: "VK.JP.19A.v1",
    dimensionId: "JP",
    subAxisId: "temporalOrientationToPlans",
    variant: "A",
    version: "v1",
    phase: 4,
    promptType: "errorDetection",
    intensity: 4,
    instructionText: "Does anything seem off?",
    modality: "text",
    stimulusRef: {
      kind: "inlineText",
      text: "A plan touts weekly checkpoints but the team consistently works in chaotic bursts. Does anything seem off?",
    },
    responseMode: "spoken",
  },
  "VK.JP.20A.v1": {
    id: "VK.JP.20A.v1",
    dimensionId: "JP",
    subAxisId: "temporalOrientationToPlans",
    variant: "A",
    version: "v1",
    phase: 5,
    promptType: "projectionContinuation",
    isWildcard: true,
    intensity: 3,
    instructionText: "What happens next?",
    modality: "text",
    stimulusRef: {
      kind: "inlineText",
      text: "Halfway through a sprint, leadership pulls the launch date two weeks closer. What happens next?",
    },
    responseMode: "spoken",
  },

  // 5) completionRelationship (IDs 21–25)
  "VK.JP.21A.v1": {
    id: "VK.JP.21A.v1",
    dimensionId: "JP",
    subAxisId: "completionRelationship",
    variant: "A",
    version: "v1",
    phase: 1,
    promptType: "freeRecall",
    intensity: 2,
    instructionText: "What do you remember?",
    modality: "text",
    stimulusRef: {
      kind: "inlineText",
      text: "You just reviewed a heat map of projects you've started versus ones you've finished. What details do you remember?",
    },
    exposureMs: 8000,
    responseMode: "spoken",
  },
  "VK.JP.22A.v1": {
    id: "VK.JP.22A.v1",
    dimensionId: "JP",
    subAxisId: "completionRelationship",
    variant: "A",
    version: "v1",
    phase: 2,
    promptType: "openInterpretation",
    intensity: 3,
    instructionText: "What do you think is happening here?",
    modality: "text",
    stimulusRef: {
      kind: "inlineText",
      text: "A clip shows someone grinning only when the last five percent is polished while another bolts as soon as the main work is done. What does that suggest about their completion relationship?",
    },
    responseMode: "spoken",
  },
  "VK.JP.23A.v1": {
    id: "VK.JP.23A.v1",
    dimensionId: "JP",
    subAxisId: "completionRelationship",
    variant: "A",
    version: "v1",
    phase: 3,
    promptType: "microDecision",
    intensity: 3,
    instructionText: "What would you do?",
    modality: "text",
    stimulusRef: {
      kind: "inlineText",
      text: "You can submit a solid draft now or hold it to chase one more improvement. What do you do?",
    },
    responseMode: "spoken",
  },
  "VK.JP.24A.v1": {
    id: "VK.JP.24A.v1",
    dimensionId: "JP",
    subAxisId: "completionRelationship",
    variant: "A",
    version: "v1",
    phase: 4,
    promptType: "errorDetection",
    intensity: 4,
    instructionText: "Does anything seem off?",
    modality: "text",
    stimulusRef: {
      kind: "inlineText",
      text: "A pipeline shows three new launches kicking off while last quarter's deliverables remain unwrapped. Does anything seem off?",
    },
    responseMode: "spoken",
  },
  "VK.JP.25A.v1": {
    id: "VK.JP.25A.v1",
    dimensionId: "JP",
    subAxisId: "completionRelationship",
    variant: "A",
    version: "v1",
    phase: 5,
    promptType: "projectionContinuation",
    isWildcard: true,
    intensity: 3,
    instructionText: "What happens next?",
    modality: "text",
    stimulusRef: {
      kind: "inlineText",
      text: "Release day ends and the dashboards go quiet. How do you continue once the thing is technically done?",
    },
    responseMode: "spoken",
  },

};

/** Fetch a prompt spec (throws if unknown). */
export function getPromptSpec(id: PromptId): PromptSpec {
  const spec = PROMPT_CATALOG[id];
  if (!spec) throw new Error(`Unknown promptId: ${id}`);
  return spec;
}

/** List prompts, optionally filtered by dimension. */
export function listPrompts(dimensionId?: PromptSpec["dimensionId"]): PromptSpec[] {
  const all = Object.values(PROMPT_CATALOG);
  return dimensionId ? all.filter(p => p.dimensionId === dimensionId) : all;
}
