// src/prompts/promptCatalog.ts
import type { PromptId, PromptSpec } from "../domain/types.js";
/**
 * Prompt catalog keyed by promptId.
 * IMPORTANT: promptId is the canonical identifier you store on each capture.
 */
export const PROMPT_CATALOG: Partial<Record<PromptId, PromptSpec>> = {

  // ======================
  // IE — SocialEnergyAxis (template: 25 prompts, A only)
  // ======================

  // 1) energyDirection (IDs 1–5)
  "VK.IE.1A.v1": {
    id: "VK.IE.1A.v1",
    dimensionId: "IE",
    subAxisId: "energyDirection",
    variant: "A",
    version: "v1",
    phase: 1,
    elicitationType: "recognition",
    intensity: 2,
    text: "You've been at a party for half an hour and the people around you are draining you with their smiling faces. Every conversation is a tiny puncture wound. You need out. Not later — now. You know the feeling?",
  },
  "VK.IE.1B.v1": {
    id: "VK.IE.1A.v1",
    dimensionId: "IE",
    subAxisId: "energyDirection",
    variant: "B",
    version: "v1",
    phase: 1,
    elicitationType: "recognition",
    intensity: 2,
    text: "You've been alone for a whole day and your own silence is driving you nuts. Not loneliness — something hungrier. Your chest is hollowing out. You need to talk to people, get outside, hear your own voice. Do you know the feeling?",
  },
  "VK.IE.2A.v1": {
    id: "VK.IE.2A.v1",
    dimensionId: "IE",
    subAxisId: "energyDirection",
    variant: "A",
    version: "v1",
    phase: 2,
    elicitationType: "painRanking",
    intensity: 3,
    text: "Which one lives closer to your skin — the feeling of being slowly dissolved by too many people in the room, or the feeling of slowly disappearing because there's no one there at all?",
  },
  "VK.IE.3A.v1": {
    id: "VK.IE.3A.v1",
    dimensionId: "IE",
    subAxisId: "energyDirection",
    variant: "A",
    version: "v1",
    phase: 3,
    elicitationType: "scenario",
    intensity: 3,
    text: "You're at a gathering with people you actually like. Three hours in. Something shifts. What hits you first — a quiet pull toward the door, like your body's leaving before you decide to… or a surge, like the room just started breathing and you want to go deeper in?",
  },
  "VK.IE.4A.v1": {
    id: "VK.IE.4A.v1",
    dimensionId: "IE",
    subAxisId: "energyDirection",
    variant: "A",
    version: "v1",
    phase: 4,
    elicitationType: "completion",
    intensity: 4,
    text: "When I've been around people too long, I start to - what?",
  },
  "VK.IE.5A.v1": {
    id: "VK.IE.5A.v1",
    dimensionId: "IE",
    subAxisId: "energyDirection",
    variant: "A",
    version: "v1",
    elicitationType: "wildCard",
    isWildcard: true,
    intensity: 3,
    text: "You're stuck in traffic. Dead stop. No music, no phone, no one in the car. Just you and the windshield. What's happening inside you after five minutes?",
  },

  // 2) processingHabitat (IDs 6–10)
  "VK.IE.6A.v1": {
    id: "VK.IE.6A.v1",
    dimensionId: "IE",
    subAxisId: "processingHabitat",
    variant: "A",
    version: "v1",
    phase: 1,
    elicitationType: "recognition",
    intensity: 2,
    text: "People keep getting you wrong. Worst part is that you can't really fix it. That would mean another performance - talking it out, explaining it, falsifying things. You just let the wrong version of you stand.",
  },
  "VK.IE.7A.v1": {
    id: "VK.IE.7A.v1",
    dimensionId: "IE",
    subAxisId: "processingHabitat",
    variant: "A",
    version: "v1",
    phase: 2,
    elicitationType: "painRanking",
    intensity: 3,
    text: "Which one cuts deeper — being consistently misread by people who'll never see the real version, or saying something real and watching it land on absolutely no one?",
  },
  "VK.IE.8A.v1": {
    id: "VK.IE.8A.v1",
    dimensionId: "IE",
    subAxisId: "processingHabitat",
    variant: "A",
    version: "v1",
    phase: 3,
    elicitationType: "scenario",
    intensity: 3,
    text: "Someone at dinner asks what you actually think about something important to you. You give a real answer. The table goes quiet for a second. What hits you first — a flare of regret, like you just handed them something they'll mishandle, or a hunger for them to come back with something, anything, so the thing you said becomes real?",
  },
  "VK.IE.9A.v1": {
    id: "VK.IE.9A.v1",
    dimensionId: "IE",
    subAxisId: "processingHabitat",
    variant: "A",
    version: "v1",
    phase: 4,
    elicitationType: "completion",
    intensity: 4,
    text: "The thing nobody gets about me is —",
  },
  "VK.IE.10A.v1": {
    id: "VK.IE.10A.v1",
    dimensionId: "IE",
    subAxisId: "processingHabitat",
    variant: "A",
    version: "v1",
    elicitationType: "wildCard",
    isWildcard: true,
    intensity: 3,
    text: "You're cooking dinner and someone in the kitchen starts telling you about their day. Long story. Lots of detail. What's happening in your body while you stir the pot?",
  },

  // 3) visibilityRelationship (IDs 11–15)
  "VK.IE.11A.v1": {
    id: "VK.IE.11A.v1",
    dimensionId: "IE",
    subAxisId: "visibilityRelationship",
    variant: "A",
    version: "v1",
    phase: 1,
    elicitationType: "recognition",
    intensity: 2,
    text: "I'm going to describe something. Tell me if you know it. Someone compliments you in front of everyone and your whole body inside tightens. It's the sudden jolting exposure. Like their eyes are assaulting you.",
  },
  "VK.IE.12A.v1": {
    id: "VK.IE.12A.v1",
    dimensionId: "IE",
    subAxisId: "visibilityRelationship",
    variant: "A",
    version: "v1",
    phase: 2,
    elicitationType: "painRanking",
    intensity: 3,
    text: "Which one wrecks you faster — being suddenly seen by everyone in the room when you weren't ready, or finding out something happened and no one thought to include you?",
  },
  "VK.IE.13A.v1": {
    id: "VK.IE.13A.v1",
    dimensionId: "IE",
    subAxisId: "visibilityRelationship",
    variant: "A",
    version: "v1",
    phase: 3,
    elicitationType: "scenario",
    intensity: 3,
    text: "You walk into work Monday morning and someone's taped a photo of you from the company party to the break room wall. People are laughing, it's friendly, no malice. What hits your body first — a jolt of exposure, skin prickling, wanting to rip it down before anyone sees you seeing it, or a warm rush, you're in the story, you're part of the thing that happened?",
  },
  "VK.IE.14A.v1": {
    id: "VK.IE.14A.v1",
    dimensionId: "IE",
    subAxisId: "visibilityRelationship",
    variant: "A",
    version: "v1",
    phase: 4,
    elicitationType: "completion",
    intensity: 4,
    text: "When all the attention is suddenly on me —",
  },
  "VK.IE.15A.v1": {
    id: "VK.IE.15A.v1",
    dimensionId: "IE",
    subAxisId: "visibilityRelationship",
    variant: "A",
    version: "v1",
    elicitationType: "wildCard",
    isWildcard: true,
    intensity: 3,
    text: "You're on a flight and the person next to you is snoring. A stranger. Incredibly annoying. Do you sit there and take it?",
  },

  // 4) connectionEconomics (IDs 16–20)
  "VK.IE.16A.v1": {
    id: "VK.IE.16A.v1",
    dimensionId: "IE",
    subAxisId: "connectionEconomics",
    variant: "A",
    version: "v1",
    phase: 1,
    elicitationType: "recognition",
    intensity: 2,
    text: "Someone tells you that you don't really know the people you love. That your connections are wide but shallow. It hits you hard — not that they're right but because your way of loving just got put on trial. Do you know this feeling?",
  },
  "VK.IE.17A.v1": {
    id: "VK.IE.17A.v1",
    dimensionId: "IE",
    subAxisId: "connectionEconomics",
    variant: "A",
    version: "v1",
    phase: 2,
    elicitationType: "painRanking",
    intensity: 3,
    text: "Which one guts you more — one of your few deep bonds going unstable, or being told the way you connect with people isn't real?",
  },
  "VK.IE.18A.v1": {
    id: "VK.IE.18A.v1",
    dimensionId: "IE",
    subAxisId: "connectionEconomics",
    variant: "A",
    version: "v1",
    phase: 3,
    elicitationType: "scenario",
    intensity: 3,
    text: "Your closest friend calls and says they need space. Indefinitely. No fight. No reason. Just space. What hits your body first — a structural panic, the floor dropping, because that bond was holding weight nothing else can carry, or a hot flash of injustice, because you've given this person everything and closeness is being treated as the problem?",
  },
  "VK.IE.19A.v1": {
    id: "VK.IE.19A.v1",
    dimensionId: "IE",
    subAxisId: "connectionEconomics",
    variant: "A",
    version: "v1",
    phase: 4,
    elicitationType: "completion",
    intensity: 4,
    text: "The people who matter most to me —",
  },
  "VK.IE.20A.v1": {
    id: "VK.IE.20A.v1",
    dimensionId: "IE",
    subAxisId: "connectionEconomics",
    variant: "A",
    version: "v1",
    elicitationType: "wildCard",
    isWildcard: true,
    intensity: 3,
    text: "You're sitting in a medical waiting room. Biopsy results pending. You might have cancer. A stranger next to you starts making small talk — weather, parking, nothing real. Do you let them in?",
  },

  // 5) restorationSignature (IDs 21–25)
  "VK.IE.21A.v1": {
    id: "VK.IE.21A.v1",
    dimensionId: "IE",
    subAxisId: "restorationSignature",
    variant: "A",
    version: "v1",
    phase: 1,
    elicitationType: "recognition",
    intensity: 2,
    text: "People are leaving, all the fun dying out. The current that was running through you drops out. Like withdrawal. Your system was running high and the line just got cut. You need more. Do you know the feeling?",
  },
  "VK.IE.22A.v1": {
    id: "VK.IE.22A.v1",
    dimensionId: "IE",
    subAxisId: "restorationSignature",
    variant: "A",
    version: "v1",
    phase: 2,
    elicitationType: "painRanking",
    intensity: 3,
    text: "Which one leaves you more desperate — finally getting alone and finding out something poisoned the silence, or the moment the people disappear and your engine has nothing left to burn?",
  },
  "VK.IE.23A.v1": {
    id: "VK.IE.23A.v1",
    dimensionId: "IE",
    subAxisId: "restorationSignature",
    variant: "A",
    version: "v1",
    phase: 3,
    elicitationType: "scenario",
    intensity: 3,
    text: "You come home after an intense day. Door closes behind you. Total silence. What moves through your body first — relief, your whole system unclenching, the walls finally holding everything out, or a drop, the momentum bleeding out of you, the quiet landing on you like sudden gravity?",
  },
  "VK.IE.24A.v1": {
    id: "VK.IE.24A.v1",
    dimensionId: "IE",
    subAxisId: "restorationSignature",
    variant: "A",
    version: "v1",
    phase: 4,
    elicitationType: "completion",
    intensity: 4,
    text: "When everything goes quiet I am —",
  },
  "VK.IE.25A.v1": {
    id: "VK.IE.25A.v1",
    dimensionId: "IE",
    subAxisId: "restorationSignature",
    variant: "A",
    version: "v1",
    elicitationType: "wildCard",
    isWildcard: true,
    intensity: 3,
    text: "You've been driving for four hours alone. Empty highway. No radio. The sun went down an hour ago and it's just your headlights and the dark. Are you at peace in there?",
  },


  // ==========================
  // NS — KnowledgeApproachAxis
  // (lowLabel is N-leaning)
  // ==========================

  // 1) attentionPlane (IDs 1–5)
  "VK.NS.1A.v1": {
    id: "VK.NS.1A.v1",
    dimensionId: "NS",
    subAxisId: "attentionPlane",
    variant: "A",
    version: "v1",
    phase: 1,
    elicitationType: "recognition",
    intensity: 2,
    text: "Tell me if you recognize this. — The grey, flattened feeling when life has been purely operational for too long. No ideas cooking. No connections firing. Like someone drained the color out of reality.",
  },
  "VK.NS.2A.v1": {
    id: "VK.NS.2A.v1",
    dimensionId: "NS",
    subAxisId: "attentionPlane",
    variant: "A",
    version: "v1",
    phase: 2,
    elicitationType: "painRanking",
    intensity: 3,
    text: "Which do you carry more — the vertigo of realizing you've been living in your head and your actual life is degrading underneath you, or the slow burn of watching someone with vision and no execution get celebrated while your hands did the real work?",
  },
  "VK.NS.3A.v1": {
    id: "VK.NS.3A.v1",
    dimensionId: "NS",
    subAxisId: "attentionPlane",
    variant: "A",
    version: "v1",
    phase: 3,
    elicitationType: "scenario",
    intensity: 3,
    text: "__TODO__",
  },
  "VK.NS.4A.v1": {
    id: "VK.NS.4A.v1",
    dimensionId: "NS",
    subAxisId: "attentionPlane",
    variant: "A",
    version: "v1",
    phase: 4,
    elicitationType: "completion",
    intensity: 4,
    text: "__TODO__",
  },
  "VK.NS.5A.v1": {
    id: "VK.NS.5A.v1",
    dimensionId: "NS",
    subAxisId: "attentionPlane",
    variant: "A",
    version: "v1",
    elicitationType: "wildCard",
    isWildcard: true,
    intensity: 3,
    text: "__TODO__",
  },

  // 2) temporalHabitat (IDs 6–10)
  "VK.NS.6A.v1": {
    id: "VK.NS.6A.v1",
    dimensionId: "NS",
    subAxisId: "temporalHabitat",
    variant: "A",
    version: "v1",
    phase: 1,
    elicitationType: "recognition",
    intensity: 2,
    text: "__TODO__",
  },
  "VK.NS.7A.v1": {
    id: "VK.NS.7A.v1",
    dimensionId: "NS",
    subAxisId: "temporalHabitat",
    variant: "A",
    version: "v1",
    phase: 2,
    elicitationType: "painRanking",
    intensity: 3,
    text: "__TODO__",
  },
  "VK.NS.8A.v1": {
    id: "VK.NS.8A.v1",
    dimensionId: "NS",
    subAxisId: "temporalHabitat",
    variant: "A",
    version: "v1",
    phase: 3,
    elicitationType: "scenario",
    intensity: 3,
    text: "__TODO__",
  },
  "VK.NS.9A.v1": {
    id: "VK.NS.9A.v1",
    dimensionId: "NS",
    subAxisId: "temporalHabitat",
    variant: "A",
    version: "v1",
    phase: 4,
    elicitationType: "completion",
    intensity: 4,
    text: "__TODO__",
  },
  "VK.NS.10A.v1": {
    id: "VK.NS.10A.v1",
    dimensionId: "NS",
    subAxisId: "temporalHabitat",
    variant: "A",
    version: "v1",
    elicitationType: "wildCard",
    isWildcard: true,
    intensity: 3,
    text: "__TODO__",
  },

  // 3) informationDiet (IDs 11–15)
  "VK.NS.11A.v1": {
    id: "VK.NS.11A.v1",
    dimensionId: "NS",
    subAxisId: "informationDiet",
    variant: "A",
    version: "v1",
    phase: 1,
    elicitationType: "recognition",
    intensity: 2,
    text: "__TODO__",
  },
  "VK.NS.12A.v1": {
    id: "VK.NS.12A.v1",
    dimensionId: "NS",
    subAxisId: "informationDiet",
    variant: "A",
    version: "v1",
    phase: 2,
    elicitationType: "painRanking",
    intensity: 3,
    text: "__TODO__",
  },
  "VK.NS.13A.v1": {
    id: "VK.NS.13A.v1",
    dimensionId: "NS",
    subAxisId: "informationDiet",
    variant: "A",
    version: "v1",
    phase: 3,
    elicitationType: "scenario",
    intensity: 3,
    text: "__TODO__",
  },
  "VK.NS.14A.v1": {
    id: "VK.NS.14A.v1",
    dimensionId: "NS",
    subAxisId: "informationDiet",
    variant: "A",
    version: "v1",
    phase: 4,
    elicitationType: "completion",
    intensity: 4,
    text: "__TODO__",
  },
  "VK.NS.15A.v1": {
    id: "VK.NS.15A.v1",
    dimensionId: "NS",
    subAxisId: "informationDiet",
    variant: "A",
    version: "v1",
    elicitationType: "wildCard",
    isWildcard: true,
    intensity: 3,
    text: "__TODO__",
  },

  // 4) realityRelationship (IDs 16–20)
  "VK.NS.16A.v1": {
    id: "VK.NS.16A.v1",
    dimensionId: "NS",
    subAxisId: "realityRelationship",
    variant: "A",
    version: "v1",
    phase: 1,
    elicitationType: "recognition",
    intensity: 2,
    text: "__TODO__",
  },
  "VK.NS.17A.v1": {
    id: "VK.NS.17A.v1",
    dimensionId: "NS",
    subAxisId: "realityRelationship",
    variant: "A",
    version: "v1",
    phase: 2,
    elicitationType: "painRanking",
    intensity: 3,
    text: "__TODO__",
  },
  "VK.NS.18A.v1": {
    id: "VK.NS.18A.v1",
    dimensionId: "NS",
    subAxisId: "realityRelationship",
    variant: "A",
    version: "v1",
    phase: 3,
    elicitationType: "scenario",
    intensity: 3,
    text: "__TODO__",
  },
  "VK.NS.19A.v1": {
    id: "VK.NS.19A.v1",
    dimensionId: "NS",
    subAxisId: "realityRelationship",
    variant: "A",
    version: "v1",
    phase: 4,
    elicitationType: "completion",
    intensity: 4,
    text: "__TODO__",
  },
  "VK.NS.20A.v1": {
    id: "VK.NS.20A.v1",
    dimensionId: "NS",
    subAxisId: "realityRelationship",
    variant: "A",
    version: "v1",
    elicitationType: "wildCard",
    isWildcard: true,
    intensity: 3,
    text: "__TODO__",
  },

  // 5) meaningThreshold (IDs 21–25)
  "VK.NS.21A.v1": {
    id: "VK.NS.21A.v1",
    dimensionId: "NS",
    subAxisId: "meaningThreshold",
    variant: "A",
    version: "v1",
    phase: 1,
    elicitationType: "recognition",
    intensity: 2,
    text: "__TODO__",
  },
  "VK.NS.22A.v1": {
    id: "VK.NS.22A.v1",
    dimensionId: "NS",
    subAxisId: "meaningThreshold",
    variant: "A",
    version: "v1",
    phase: 2,
    elicitationType: "painRanking",
    intensity: 3,
    text: "__TODO__",
  },
  "VK.NS.23A.v1": {
    id: "VK.NS.23A.v1",
    dimensionId: "NS",
    subAxisId: "meaningThreshold",
    variant: "A",
    version: "v1",
    phase: 3,
    elicitationType: "scenario",
    intensity: 3,
    text: "__TODO__",
  },
  "VK.NS.24A.v1": {
    id: "VK.NS.24A.v1",
    dimensionId: "NS",
    subAxisId: "meaningThreshold",
    variant: "A",
    version: "v1",
    phase: 4,
    elicitationType: "completion",
    intensity: 4,
    text: "__TODO__",
  },
  "VK.NS.25A.v1": {
    id: "VK.NS.25A.v1",
    dimensionId: "NS",
    subAxisId: "meaningThreshold",
    variant: "A",
    version: "v1",
    elicitationType: "wildCard",
    isWildcard: true,
    intensity: 3,
    text: "__TODO__",
  },


  // ======================
  // TF — DecisionStyleAxis
  // ======================

  // 1) evaluationReflex (IDs 1–5)
  "VK.TF.1A.v1": {
    id: "VK.TF.1A.v1",
    dimensionId: "TF",
    subAxisId: "evaluationReflex",
    variant: "A",
    version: "v1",
    phase: 1,
    elicitationType: "recognition",
    intensity: 2,
    text: "Tell me if you recognize this. — The sharp discomfort of watching someone make a decision based entirely on how they feel about it, when the evidence is sitting right there being ignored.",
  },
  "VK.TF.2A.v1": {
    id: "VK.TF.2A.v1",
    dimensionId: "TF",
    subAxisId: "evaluationReflex",
    variant: "A",
    version: "v1",
    phase: 2,
    elicitationType: "painRanking",
    intensity: 3,
    text: "Which lives closer to your skin — the loneliness of being right when everyone hates you for it, or the sickness of keeping the peace when you swallowed something true?",
  },
  "VK.TF.3A.v1": {
    id: "VK.TF.3A.v1",
    dimensionId: "TF",
    subAxisId: "evaluationReflex",
    variant: "A",
    version: "v1",
    phase: 3,
    elicitationType: "scenario",
    intensity: 3,
    text: "__TODO__",
  },
  "VK.TF.4A.v1": {
    id: "VK.TF.4A.v1",
    dimensionId: "TF",
    subAxisId: "evaluationReflex",
    variant: "A",
    version: "v1",
    phase: 4,
    elicitationType: "completion",
    intensity: 4,
    text: "__TODO__",
  },
  "VK.TF.5A.v1": {
    id: "VK.TF.5A.v1",
    dimensionId: "TF",
    subAxisId: "evaluationReflex",
    variant: "A",
    version: "v1",
    elicitationType: "wildCard",
    isWildcard: true,
    intensity: 3,
    text: "__TODO__",
  },

  // 2) truthOrientation (IDs 6–10)
  "VK.TF.6A.v1": {
    id: "VK.TF.6A.v1",
    dimensionId: "TF",
    subAxisId: "truthOrientation",
    variant: "A",
    version: "v1",
    phase: 1,
    elicitationType: "recognition",
    intensity: 2,
    text: "__TODO__",
  },
  "VK.TF.7A.v1": {
    id: "VK.TF.7A.v1",
    dimensionId: "TF",
    subAxisId: "truthOrientation",
    variant: "A",
    version: "v1",
    phase: 2,
    elicitationType: "painRanking",
    intensity: 3,
    text: "__TODO__",
  },
  "VK.TF.8A.v1": {
    id: "VK.TF.8A.v1",
    dimensionId: "TF",
    subAxisId: "truthOrientation",
    variant: "A",
    version: "v1",
    phase: 3,
    elicitationType: "scenario",
    intensity: 3,
    text: "__TODO__",
  },
  "VK.TF.9A.v1": {
    id: "VK.TF.9A.v1",
    dimensionId: "TF",
    subAxisId: "truthOrientation",
    variant: "A",
    version: "v1",
    phase: 4,
    elicitationType: "completion",
    intensity: 4,
    text: "__TODO__",
  },
  "VK.TF.10A.v1": {
    id: "VK.TF.10A.v1",
    dimensionId: "TF",
    subAxisId: "truthOrientation",
    variant: "A",
    version: "v1",
    elicitationType: "wildCard",
    isWildcard: true,
    intensity: 3,
    text: "__TODO__",
  },

  // 3) decisionSubstrate (IDs 11–15)
  "VK.TF.11A.v1": {
    id: "VK.TF.11A.v1",
    dimensionId: "TF",
    subAxisId: "decisionSubstrate",
    variant: "A",
    version: "v1",
    phase: 1,
    elicitationType: "recognition",
    intensity: 2,
    text: "__TODO__",
  },
  "VK.TF.12A.v1": {
    id: "VK.TF.12A.v1",
    dimensionId: "TF",
    subAxisId: "decisionSubstrate",
    variant: "A",
    version: "v1",
    phase: 2,
    elicitationType: "painRanking",
    intensity: 3,
    text: "__TODO__",
  },
  "VK.TF.13A.v1": {
    id: "VK.TF.13A.v1",
    dimensionId: "TF",
    subAxisId: "decisionSubstrate",
    variant: "A",
    version: "v1",
    phase: 3,
    elicitationType: "scenario",
    intensity: 3,
    text: "__TODO__",
  },
  "VK.TF.14A.v1": {
    id: "VK.TF.14A.v1",
    dimensionId: "TF",
    subAxisId: "decisionSubstrate",
    variant: "A",
    version: "v1",
    phase: 4,
    elicitationType: "completion",
    intensity: 4,
    text: "__TODO__",
  },
  "VK.TF.15A.v1": {
    id: "VK.TF.15A.v1",
    dimensionId: "TF",
    subAxisId: "decisionSubstrate",
    variant: "A",
    version: "v1",
    elicitationType: "wildCard",
    isWildcard: true,
    intensity: 3,
    text: "__TODO__",
  },

  // 4) conflictMetabolism (IDs 16–20)
  "VK.TF.16A.v1": {
    id: "VK.TF.16A.v1",
    dimensionId: "TF",
    subAxisId: "conflictMetabolism",
    variant: "A",
    version: "v1",
    phase: 1,
    elicitationType: "recognition",
    intensity: 2,
    text: "__TODO__",
  },
  "VK.TF.17A.v1": {
    id: "VK.TF.17A.v1",
    dimensionId: "TF",
    subAxisId: "conflictMetabolism",
    variant: "A",
    version: "v1",
    phase: 2,
    elicitationType: "painRanking",
    intensity: 3,
    text: "__TODO__",
  },
  "VK.TF.18A.v1": {
    id: "VK.TF.18A.v1",
    dimensionId: "TF",
    subAxisId: "conflictMetabolism",
    variant: "A",
    version: "v1",
    phase: 3,
    elicitationType: "scenario",
    intensity: 3,
    text: "__TODO__",
  },
  "VK.TF.19A.v1": {
    id: "VK.TF.19A.v1",
    dimensionId: "TF",
    subAxisId: "conflictMetabolism",
    variant: "A",
    version: "v1",
    phase: 4,
    elicitationType: "completion",
    intensity: 4,
    text: "__TODO__",
  },
  "VK.TF.20A.v1": {
    id: "VK.TF.20A.v1",
    dimensionId: "TF",
    subAxisId: "conflictMetabolism",
    variant: "A",
    version: "v1",
    elicitationType: "wildCard",
    isWildcard: true,
    intensity: 3,
    text: "__TODO__",
  },

  // 5) boundaryArchitecture (IDs 21–25)
  "VK.TF.21A.v1": {
    id: "VK.TF.21A.v1",
    dimensionId: "TF",
    subAxisId: "boundaryArchitecture",
    variant: "A",
    version: "v1",
    phase: 1,
    elicitationType: "recognition",
    intensity: 2,
    text: "__TODO__",
  },
  "VK.TF.22A.v1": {
    id: "VK.TF.22A.v1",
    dimensionId: "TF",
    subAxisId: "boundaryArchitecture",
    variant: "A",
    version: "v1",
    phase: 2,
    elicitationType: "painRanking",
    intensity: 3,
    text: "__TODO__",
  },
  "VK.TF.23A.v1": {
    id: "VK.TF.23A.v1",
    dimensionId: "TF",
    subAxisId: "boundaryArchitecture",
    variant: "A",
    version: "v1",
    phase: 3,
    elicitationType: "scenario",
    intensity: 3,
    text: "__TODO__",
  },
  "VK.TF.24A.v1": {
    id: "VK.TF.24A.v1",
    dimensionId: "TF",
    subAxisId: "boundaryArchitecture",
    variant: "A",
    version: "v1",
    phase: 4,
    elicitationType: "completion",
    intensity: 4,
    text: "__TODO__",
  },
  "VK.TF.25A.v1": {
    id: "VK.TF.25A.v1",
    dimensionId: "TF",
    subAxisId: "boundaryArchitecture",
    variant: "A",
    version: "v1",
    elicitationType: "wildCard",
    isWildcard: true,
    intensity: 3,
    text: "__TODO__",
  },


  // ======================
  // JP — ActionStrategyAxis
  // ======================

  // 1) closureDrive (IDs 1–5)
  "VK.JP.1A.v1": {
    id: "VK.JP.1A.v1",
    dimensionId: "JP",
    subAxisId: "closureDrive",
    variant: "A",
    version: "v1",
    phase: 1,
    elicitationType: "recognition",
    intensity: 2,
    text: "Tell me if you recognize this. — The mounting agitation of something unresolved. An open loop your mind keeps circling back to, burning background cycles on a process that won't terminate.",
  },
  "VK.JP.2A.v1": {
    id: "VK.JP.2A.v1",
    dimensionId: "JP",
    subAxisId: "closureDrive",
    variant: "A",
    version: "v1",
    phase: 2,
    elicitationType: "painRanking",
    intensity: 3,
    text: "Which keeps you up — the suspicion that you locked something down too early and a better option arrived after the door closed, or the dread that your refusal to commit has left you standing in a hallway of open doors you never walked through?",
  },
  "VK.JP.3A.v1": {
    id: "VK.JP.3A.v1",
    dimensionId: "JP",
    subAxisId: "closureDrive",
    variant: "A",
    version: "v1",
    phase: 3,
    elicitationType: "scenario",
    intensity: 3,
    text: "__TODO__",
  },
  "VK.JP.4A.v1": {
    id: "VK.JP.4A.v1",
    dimensionId: "JP",
    subAxisId: "closureDrive",
    variant: "A",
    version: "v1",
    phase: 4,
    elicitationType: "completion",
    intensity: 4,
    text: "__TODO__",
  },
  "VK.JP.5A.v1": {
    id: "VK.JP.5A.v1",
    dimensionId: "JP",
    subAxisId: "closureDrive",
    variant: "A",
    version: "v1",
    elicitationType: "wildCard",
    isWildcard: true,
    intensity: 3,
    text: "__TODO__",
  },

  // 2) structureRelationship (IDs 6–10)
  "VK.JP.6A.v1": {
    id: "VK.JP.6A.v1",
    dimensionId: "JP",
    subAxisId: "structureRelationship",
    variant: "A",
    version: "v1",
    phase: 1,
    elicitationType: "recognition",
    intensity: 2,
    text: "__TODO__",
  },
  "VK.JP.7A.v1": {
    id: "VK.JP.7A.v1",
    dimensionId: "JP",
    subAxisId: "structureRelationship",
    variant: "A",
    version: "v1",
    phase: 2,
    elicitationType: "painRanking",
    intensity: 3,
    text: "__TODO__",
  },
  "VK.JP.8A.v1": {
    id: "VK.JP.8A.v1",
    dimensionId: "JP",
    subAxisId: "structureRelationship",
    variant: "A",
    version: "v1",
    phase: 3,
    elicitationType: "scenario",
    intensity: 3,
    text: "__TODO__",
  },
  "VK.JP.9A.v1": {
    id: "VK.JP.9A.v1",
    dimensionId: "JP",
    subAxisId: "structureRelationship",
    variant: "A",
    version: "v1",
    phase: 4,
    elicitationType: "completion",
    intensity: 4,
    text: "__TODO__",
  },
  "VK.JP.10A.v1": {
    id: "VK.JP.10A.v1",
    dimensionId: "JP",
    subAxisId: "structureRelationship",
    variant: "A",
    version: "v1",
    elicitationType: "wildCard",
    isWildcard: true,
    intensity: 3,
    text: "__TODO__",
  },

  // 3) commitmentMetabolism (IDs 11–15)
  "VK.JP.11A.v1": {
    id: "VK.JP.11A.v1",
    dimensionId: "JP",
    subAxisId: "commitmentMetabolism",
    variant: "A",
    version: "v1",
    phase: 1,
    elicitationType: "recognition",
    intensity: 2,
    text: "__TODO__",
  },
  "VK.JP.12A.v1": {
    id: "VK.JP.12A.v1",
    dimensionId: "JP",
    subAxisId: "commitmentMetabolism",
    variant: "A",
    version: "v1",
    phase: 2,
    elicitationType: "painRanking",
    intensity: 3,
    text: "__TODO__",
  },
  "VK.JP.13A.v1": {
    id: "VK.JP.13A.v1",
    dimensionId: "JP",
    subAxisId: "commitmentMetabolism",
    variant: "A",
    version: "v1",
    phase: 3,
    elicitationType: "scenario",
    intensity: 3,
    text: "__TODO__",
  },
  "VK.JP.14A.v1": {
    id: "VK.JP.14A.v1",
    dimensionId: "JP",
    subAxisId: "commitmentMetabolism",
    variant: "A",
    version: "v1",
    phase: 4,
    elicitationType: "completion",
    intensity: 4,
    text: "__TODO__",
  },
  "VK.JP.15A.v1": {
    id: "VK.JP.15A.v1",
    dimensionId: "JP",
    subAxisId: "commitmentMetabolism",
    variant: "A",
    version: "v1",
    elicitationType: "wildCard",
    isWildcard: true,
    intensity: 3,
    text: "__TODO__",
  },

  // 4) temporalOrientationToPlans (IDs 16–20)
  "VK.JP.16A.v1": {
    id: "VK.JP.16A.v1",
    dimensionId: "JP",
    subAxisId: "temporalOrientationToPlans",
    variant: "A",
    version: "v1",
    phase: 1,
    elicitationType: "recognition",
    intensity: 2,
    text: "__TODO__",
  },
  "VK.JP.17A.v1": {
    id: "VK.JP.17A.v1",
    dimensionId: "JP",
    subAxisId: "temporalOrientationToPlans",
    variant: "A",
    version: "v1",
    phase: 2,
    elicitationType: "painRanking",
    intensity: 3,
    text: "__TODO__",
  },
  "VK.JP.18A.v1": {
    id: "VK.JP.18A.v1",
    dimensionId: "JP",
    subAxisId: "temporalOrientationToPlans",
    variant: "A",
    version: "v1",
    phase: 3,
    elicitationType: "scenario",
    intensity: 3,
    text: "__TODO__",
  },
  "VK.JP.19A.v1": {
    id: "VK.JP.19A.v1",
    dimensionId: "JP",
    subAxisId: "temporalOrientationToPlans",
    variant: "A",
    version: "v1",
    phase: 4,
    elicitationType: "completion",
    intensity: 4,
    text: "__TODO__",
  },
  "VK.JP.20A.v1": {
    id: "VK.JP.20A.v1",
    dimensionId: "JP",
    subAxisId: "temporalOrientationToPlans",
    variant: "A",
    version: "v1",
    elicitationType: "wildCard",
    isWildcard: true,
    intensity: 3,
    text: "__TODO__",
  },

  // 5) completionRelationship (IDs 21–25)
  "VK.JP.21A.v1": {
    id: "VK.JP.21A.v1",
    dimensionId: "JP",
    subAxisId: "completionRelationship",
    variant: "A",
    version: "v1",
    phase: 1,
    elicitationType: "recognition",
    intensity: 2,
    text: "__TODO__",
  },
  "VK.JP.22A.v1": {
    id: "VK.JP.22A.v1",
    dimensionId: "JP",
    subAxisId: "completionRelationship",
    variant: "A",
    version: "v1",
    phase: 2,
    elicitationType: "painRanking",
    intensity: 3,
    text: "__TODO__",
  },
  "VK.JP.23A.v1": {
    id: "VK.JP.23A.v1",
    dimensionId: "JP",
    subAxisId: "completionRelationship",
    variant: "A",
    version: "v1",
    phase: 3,
    elicitationType: "scenario",
    intensity: 3,
    text: "__TODO__",
  },
  "VK.JP.24A.v1": {
    id: "VK.JP.24A.v1",
    dimensionId: "JP",
    subAxisId: "completionRelationship",
    variant: "A",
    version: "v1",
    phase: 4,
    elicitationType: "completion",
    intensity: 4,
    text: "__TODO__",
  },
  "VK.JP.25A.v1": {
    id: "VK.JP.25A.v1",
    dimensionId: "JP",
    subAxisId: "completionRelationship",
    variant: "A",
    version: "v1",
    elicitationType: "wildCard",
    isWildcard: true,
    intensity: 3,
    text: "__TODO__",
  },

};

/** Fetch a prompt spec (throws if unknown). */
export function getPromptSpec(id: PromptId): PromptSpec {
  const spec = PROMPT_CATALOG[id];
  if (!spec) throw new Error(`Unknown promptId: ${id}`);
  return spec;
}

/** List prompts, optionally filtered by dimension. */
export function listPrompts(dimensionId?: PromptSpec["dimensionId"]): PromptSpec[] {
  const all = Object.values(PROMPT_CATALOG);
  return dimensionId ? all.filter(p => p.dimensionId === dimensionId) : all;
}